[build]
  base = "."
  command = "echo 'No build required for Streamlit app'"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/streamlit_main.py"
  status = 200
